"""Build local 4x texture comparisons; render vector geometry at 8x first.

AI inputs are manually supplied imagegen outputs, never generated by this script.
"""
import argparse
import json
import subprocess
import xml.etree.ElementTree as ET
from pathlib import Path
import numpy as np
from PIL import Image
from trace import trace

DLL=r'C:\Program Files\Inkscape\bin\libpotrace-0.dll'
INKSCAPE=r'C:\Program Files\Inkscape\bin\inkscape.com'
SAMPLES=[('fighter','99a91d5ea5f56334','Flat ability badge'),
         ('dedede','dc95c1e8b19bf0fd','Shaded portrait'),
         ('parasol','dea9383a5ad91e85','Illustrated card')]

def resize_rgba(image,size):
    """Lanczos in linear light with premultiplied alpha, avoiding hidden RGB bleed."""
    v=np.asarray(image.convert('RGBA'),dtype=np.float32)/255
    rgb=np.where(v[:,:,:3]<=.04045,v[:,:,:3]/12.92,((v[:,:,:3]+.055)/1.055)**2.4)
    a=v[:,:,3:4]
    channels=np.concatenate((rgb*a,a),axis=2)
    out=np.stack([np.asarray(Image.fromarray(channels[:,:,i]).resize(size,Image.Resampling.LANCZOS)) for i in range(4)],axis=2)
    alpha=np.clip(out[:,:,3:4],0,1)
    rgb=np.clip(out[:,:,:3]/np.maximum(alpha,1e-7),0,1)
    rgb=np.where(rgb<=.0031308,rgb*12.92,1.055*rgb**(1/2.4)-.055)
    rgb=np.where(alpha>1e-7,rgb,0)
    return Image.fromarray(np.rint(np.concatenate((rgb,alpha),axis=2)*255).astype(np.uint8))

def mask_path(mask,folder,name):
    source=folder/(name+'-mask.png');svg=folder/(name+'-mask.svg')
    Image.merge('RGBA',(mask,mask,mask,mask)).save(source)
    report=trace(source,svg,DLL,speckles=0,corners=1,tolerance=.15)
    return ET.parse(svg).getroot()[0].attrib['d'],report

def svg_file(folder,name,size,paths):
    w,h=size
    text=f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}">'
    text+=''.join(f'<path fill="{color}" fill-rule="evenodd" d="{d}"/>' for color,d in paths)+'</svg>'
    p=folder/(name+'.svg');p.write_text(text)
    out=folder/(name+'-8x.png')
    subprocess.run([INKSCAPE,str(p),'--export-type=png','--export-filename='+str(out),f'--export-width={w*8}',f'--export-height={h*8}'],check=True,capture_output=True)
    return Image.open(out).convert('RGBA')

def flat_vector(im,folder):
    # Two dominant colors, estimated only from fully opaque source pixels.
    v=np.asarray(im);points=v[:,:,:3][v[:,:,3]==255].astype(float)
    centers=np.array([points[np.argmin(points[:,1])],points[np.argmax(points[:,1])]])
    for _ in range(16):
        labels=((points[:,None]-centers[None])**2).sum(2).argmin(1)
        centers=np.array([np.median(points[labels==i],axis=0) for i in range(2)])
    centers=centers[np.argsort(centers[:,1])]
    labels=((v[:,:,:3,None].transpose(0,1,3,2)-centers)**2).sum(3).argmin(2)
    silhouette,report=mask_path(im.getchannel('A'),folder,'silhouette')
    interior=Image.fromarray(((labels==1)&(v[:,:,3]>=128)).astype(np.uint8)*255)
    interior_path,inner_report=mask_path(interior,folder,'interior')
    colors=['#%02x%02x%02x'%tuple(c.astype(int)) for c in centers]
    hi=svg_file(folder,'two-color',im.size,[(colors[0],silhouette),(colors[1],interior_path)])
    return hi,dict(colors=colors,silhouette=report,interior=inner_report)

def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--assets',type=Path,default=Path('assets/kirby'))
    p.add_argument('--output',type=Path,default=Path('assets/kirby/demos'))
    p.add_argument('--ai-dir',type=Path,default=Path('work/ai-demos'))
    args=p.parse_args();args.output.mkdir(parents=True,exist_ok=True)
    records=json.loads((args.assets/'manifest.json').read_text())
    result=[]
    for name,identity,title in SAMPLES:
        rec=next(r for r in records if r['id']==identity)
        im=Image.open(args.assets/rec['file']).convert('RGBA')
        folder=args.output/name;folder.mkdir(exist_ok=True)
        im.save(folder/'source.png');size=(im.width*4,im.height*4)
        baseline=resize_rgba(im,size);baseline.save(folder/'baseline-4x.png')
        im.resize(size,Image.Resampling.NEAREST).save(folder/'nearest-4x.png')
        item=dict(name=name,title=title,source=rec,final_size=size,oversample_factor=2,
                  variants=[['Native pixels','nearest-4x.png'],['Linear premultiplied Lanczos','baseline-4x.png']])
        if name=='fighter':
            high,detail=flat_vector(im,folder)
            resize_rgba(high,size).save(folder/'vector-4x.png')
            item['trace']=detail;item['variants'].append(['Two-color Potrace · 8x → 4x','vector-4x.png'])
        else:
            outline,detail=mask_path(im.getchannel('A'),folder,'silhouette')
            matte=svg_file(folder,'alpha',im.size,[('#ffffff',outline)]).getchannel('A')
            source_high=resize_rgba(im,(im.width*8,im.height*8))
            raster_vector=source_high.copy();raster_vector.putalpha(matte)
            resize_rgba(raster_vector,size).save(folder/'raster-vector-4x.png')
            item['variants'].append(['Original color + vector silhouette','raster-vector-4x.png'])
            ai_path=args.ai_dir/(name+'.png')
            if ai_path.exists():
                ai=Image.open(ai_path).convert('RGBA');item['ai_native_size']=ai.size
                item['ai_status']='Rejected: changed content and background defects'
                item['ai_detail_scale_vs_final']=[ai.width/size[0],ai.height/size[1]]
                item['ai_method']='Built-in imagegen generative reconstruction, not a dedicated super-resolution model'
                # Retain returned dimensions in metadata; resizing does not create model detail.
                ai.save(folder/'ai-returned.png')
                high=resize_rgba(ai,(im.width*8,im.height*8))
                resize_rgba(high,size).save(folder/'ai-4x.png')
                # Keep original silhouette, blend AI color only inside it. Inspect for alignment drift.
                color=Image.alpha_composite(source_high,high)
                color.putalpha(matte)
                resize_rgba(color,size).save(folder/'hybrid-4x.png')
                item['trace']=detail
                item['variants'] += [['Rejected AI reconstruction','ai-4x.png'],['Rejected AI + vector silhouette','hybrid-4x.png']]
        result.append(item)
    (args.output/'demo-manifest.json').write_text(json.dumps(result,indent=2))
    html='''<!doctype html><meta charset="utf-8"><title>Kirby upscale demos</title>
<style>body{background:#191b22;color:#eee;font:16px system-ui;margin:24px}a{color:#afd3ff}.row{display:flex;gap:16px;overflow:auto}.cell{min-width:260px;width:calc(25% - 12px)}img{width:100%;height:340px;object-fit:contain;background:repeating-conic-gradient(#555 0% 25%,#888 0% 50%) 0/20px 20px}.cell p{min-height:44px}small{color:#bbc}section{margin:35px 0}button{padding:8px}body.white img{background:white}body.black img{background:black}</style>
<h1>Kirby upscale demos</h1><p>4× output. Vector and hybrid candidates render at 8×, then reduce in linear light with premultiplied alpha.</p>
<p><a href="curvature.html">Compare Mean Curvature Blur: iterations 0–3 at two processing sizes</a></p>
<p>AI reconstruction changed details. Both AI samples are rejected. These are comparisons, not approved replacement textures. Click any image for the full-size PNG.</p>
<p>The AI tool did not honor requested output sizes. Returned resolution is shown below. Enlarging to the 8× processing canvas adds no model detail.</p>
<button onclick="document.body.className=''">Checkerboard</button> <button onclick="document.body.className='white'">White</button> <button onclick="document.body.className='black'">Black</button>
'''
    for r in result:
        html+=f'<section><h2>{r["title"]}</h2><small>Source {r["source"]["width"]} × {r["source"]["height"]}; output {r["final_size"][0]} × {r["final_size"][1]}</small><div class="row">'
        if 'ai_native_size' in r:
            html=html.removesuffix('<div class="row">')+f'<p>AI returned {r["ai_native_size"][0]} × {r["ai_native_size"][1]}. Generative reconstruction; not a dedicated super-resolution model.</p><div class="row">'
        for label,file in r['variants']:
            link=r['name']+'/'+file
            html+=f'<div class="cell"><p>{label}</p><a href="{link}" target="_blank"><img src="{link}"></a></div>'
        html+='</div></section>'
    (args.output/'index.html').write_text(html,encoding='utf-8')
    print(json.dumps([dict(name=r['name'],variants=len(r['variants']),ai_native_size=r.get('ai_native_size')) for r in result]))

if __name__=='__main__':main()
